### ISSUE TITLE
Wrapped VAST is not playing

### ISSUE THREAD

**Issue by yonida** [MailOnline/videojs-vast-vpaid#102]
I got this wrapped vast tag: http://projects.kaltura.com/ran/xml/vast_wrapper.xml
When running it with the player, I don't get the ad.
On the other hand, it works on JW test page: http://demo.jwplayer.com/ad-tester/
When I debug the player, it looks like the inner vast returns MediaFile of type video/x-mp4, and ```tech.canPlaySource(source)``` returns an empty string for this.
Is this a videojs issue?

**Comment by Fetz** [comment]
Hi @yonida I tried to test that VAST. But when I use it in VAST/VPAID tag in the demo or using custom XML I get this error in IOS:

![screen shot 2016-01-15 at 11 11 59](https://cloud.githubusercontent.com/assets/1071113/12351845/e2ca785a-bb78-11e5-9a50-515c449a3f33.png)

and in Chrome desktop:

`XMLHttpRequest cannot load http://projects.kaltura.com/ran/xml/vast_wrapper.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mailonline.github.io' is therefore not allowed access.`

Is only working in JW test page: http://demo.jwplayer.com/ad-tester/ is because the player is in flash (flash handles CORS differently).

For more details see this other issues:
https://github.com/MailOnline/videojs-vast-vpaid/issues?utf8=%E2%9C%93&q=is%3Aissue+CORS+
http://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf page 16
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
