### ISSUE TITLE
videojs dash compatibility

### ISSUE THREAD

**Issue by StaymanHou** [MailOnline/videojs-vast-vpaid#121]
wonder whether this plugin works with the videojs dash plugin? https://github.com/videojs/videojs-contrib-dash

**Comment by Fetz** [comment]
I don't think so, since we not supporting yet videojs 5x, you can try to use that plugin with videojs 4x.

We are working in videojs-vast-vpaid to add support to videojs 5x and 4x in this branch (https://github.com/MailOnline/videojs-vast-vpaid/tree/videojs-5x).

If there is any issue using that plugin lets us know since we want to add that functionality as well at mailonline.

**Comment by StaymanHou** [comment]
Thanks for the reploy. I'll probably try it out myself.

**Comment by massa84** [comment]
videojs 5x branch has been merged into master branche and we release the videojs.vast.vpaid plugin version 1.0

**Comment by Danovadia** [comment]
Hi

Im trying the dome site with this vpaid:
http://p.algovid.com/vpvast?p=99974228&sid=[SUBID]&cb=[CB]&d=viralwiz.com&w=300&h=250

And for some reason i get no ads.

What can be the problem?

**Comment by baqarrivi** [comment]
i have integreated dash in the wordpress plugin . and have try to use it but it is not working in it .! if not please tell me which one will work :/

**Comment by clintonbosch** [comment]
It seems there is a compatibility issue with this plugin and the dash plugin. If I am using dash plugin along with this one, it seems the player then plays the ad again after the initial play instead of playing the actual source video. If I remove the dash plugin then it work fine. PLEASE PLEASE PLEASE could you get these 2 plugins to play nicely as I am desperate to have them both
