### ISSUE TITLE
videojs-vast-vpaid together with videojs-youtube: neither ad nor content is played

### ISSUE THREAD

**Issue by derdeka** [MailOnline/videojs-vast-vpaid#15]
`videojs-vast-vpaid` with a locally hosted content video works great with vast and vpaid swf advertisements, thanks for the great work.

### Issue

I've tried to setup `videojs-vast-vpaid` with `videojs-youtube` as a tech provider. When hitting the play button, nothing happens. Neither the ad is playing nor the content.

- If I comment out the `videojs-vast--vpaid` plugin, the youtube video is played correctly.
- If I comment out the youtube `techOrder` and use a local video (but not the `videojs-vast-vpaid` plugin), the ad plays correctly.

Does anybody have some suggestions to get this working?

### Example

https://gist.github.com/derdeka/f6d47ae8c8c0d52b7bb5

*bower.json*

    {
      "name": "videojstest2",
      "version": "0.0.1",
      "dependencies": {
        "videojs-vast-vpaid": "~0.0.38",
        "es5-shim": "~4.1.10",
        "xhook": "~1.3.0",
        "videojs": "~4.12.12",
        "normalize-css": "~3.0.3",
        "videojs-youtube": "~1.2.12"
      }
    }

**Comment by carpasse** [comment]
@derdeka Thanks for pointing this out
We are going to take a look at it.

**Comment by derdeka** [comment]
@Fetz: tagging with "3rd party" means this is a bug in videojs-youtube? Any idea what is causing this?

**Comment by Fetz** [comment]
@derdeka 3rd party means that we need to investigate our plugin integration with other plugin only that.

**Comment by Fetz** [comment]
@carpasse, @derdeka for some reason the black poster is blocking the click making the video not clickable.

```html
<div class="vjs-black-poster"></div>
```

@derdeka for now what you can do is hide the element (I tested and is working ok) or try to see if you add an event listener to click event to play the video

**Comment by Fetz** [comment]
@derdeka after some investigations we found that the problem is that the videojs-youtube plugin disables click event in the poster, disabling the default behaviour of videojs.

Because the issue is caused by videojs-youtube plugin disabling default behaviour of videojs, we will not 
add a workaround in the plugin, but I offer some solutions below...

Solutions
------------

- or disable the css rule that the plugin sets in the poster will fix the issue (maybe is there for some reason? contact the plugin developer to get more info)

![snap 2015-09-08 at 15 56 13 1345x121](https://cloud.githubusercontent.com/assets/1071113/9738203/5ff13f54-5642-11e5-9922-16d98954b2a1.png)

- or you can hide our black poster (not recommended because is there to fix issues on slow browsers)
- or add an event listener to the blackposter to play the video (maybe only when the youtube plugin is running, that will cause less issues)

![snap 2015-09-07 at 20 04 08 558x272](https://cloud.githubusercontent.com/assets/1071113/9738267/a29e76f0-5642-11e5-95ad-b57fcdc20196.png)
