### ISSUE TITLE
Getting the current src (of the Ad Unit)

### ISSUE THREAD

**Issue by orcaman** [MailOnline/videojs-vast-vpaid#18]
Hey guys,

Any chance you could add the adUnit object something like a source property that would indicate the source of the video ad currently playing (e.g. coolAd.flv)? 

Cheers

**Comment by Fetz** [comment]
This looks like a cool feature for debugging, we will ad to the adunit object

**Comment by orcaman** [comment]
I'm wondering - do you think it will be possible to obtain the URL of the actual ad? So if for example the the VAST returned a VPAID player (say Adap.tv ad manager), but the actual ad that's being played is something like http://some.cdn.com/video-ads/toyoya-ad.flv, we would get the toyota-ad.flv url? I guess this would be hard to do (since the SWF/admanager playing the video is not under our control).

**Comment by carpasse** [comment]
On VAST the src would be the video src that we set on the player, but on VPAID would be the src of the executable ad. A SWF file on Flash VPAID and a JS file on Html5 VPAID.

Would that be good for you?

**Comment by carpasse** [comment]
I have added a getSrc method to the player.vast.adUnit obj that contains the [MediaFile](https://github.com/MailOnline/videojs-vast-vpaid/blob/master/src/ads/vast/client/MediaFile.js) instance used to play the add. 

@orcaman I think this should be what you were requesting. 
We will do a release with the change through the day.

**Comment by orcaman** [comment]
@carpasse Great, thanks

**Comment by ABHISHEKG004** [comment]
hello guys,

Can anyone tell how to fetch the **.flv ** videoads url from the swf file of vpaidflash ads?

**Comment by carpasse** [comment]
You would have to decompile the swf file. 
I have no idea on how to do it sorry

**Comment by Fetz** [comment]
@ABHISHEKG004 you can use https://www.wireshark.org/ or https://www.charlesproxy.com/ or fiddler

**Comment by ABHISHEKG004** [comment]
@Fetz  and @carpasse  i have already decompiled the .swf file of the given ad but in that file there is no link given related to .flv file of that ad. Can anyone please tell me how to fetch the .flv url of the video ad programmactically using the .swf file so that i can use it directly in the main **videojs-vast-vpaid.js** file?

**Comment by orcaman** [comment]
@ABHISHEKG004 I guess what you want to do is to be able to capture the URL of the media file in runtime. In VPAID Flash this isn't possible. The Flash VPAID component loads up another SWF file, and that SWF file eventually plays the ad on it's on. At no point the media file being played on the child SWF is exposed to the parent so there is no way you can achieve this. The only way to capture the URL of the media file is by using a proxy as mentioned in the previous comments - and then you could later use that URL however you like (but I guess this is not what you are after - you wouldn't be able to do this on an arbitrary client machine, only on machines that have your proxy running).

**Comment by ABHISHEKG004** [comment]
@orcaman  thanks for clearing my misconception.... I want to ask one thing, actually i want to share the ad file i.e swf file so that whoever opens that link can see the ad video playing but by sharing the swf file it is not possible to play that file. Is there any method such that i can share that swf file so that whoever opens that link can see that ad video playing?
