### ISSUE TITLE
Does the plugin support skippable?

### ISSUE THREAD

**Issue by kewun** [MailOnline/videojs-vast-vpaid#34]
I couldn't seem to find any way of enabling skippable for preroll. Is this implemented? Or are there plans to implement this?

**Comment by Fetz** [comment]
Yes is implemented and is automatic. When we receive the event **AdSkippableStateChange** we add a div with the text skip add.
Is a bit rare to get this event in VPAID (because is only supported in VPAID 2.0, and we are dependent of the ad to fire this event   **AdSkippableStateChange**  - check skipAd method).

I manually fired the event in the Ad to show this images below

![snap 2015-08-28 at 12 14 02 432x243](https://cloud.githubusercontent.com/assets/1071113/9545135/9275aa4a-4d7e-11e5-9d80-d0f7f6b3275a.png)

![snap 2015-08-28 at 12 14 47 595x125](https://cloud.githubusercontent.com/assets/1071113/9545137/9c032682-4d7e-11e5-85f4-4ec8a2febf3c.png)


![snap 2015-08-28 at 12 15 13 331x286](https://cloud.githubusercontent.com/assets/1071113/9545144/a24f2cfc-4d7e-11e5-8fc3-4f37ffdf3c91.png)

**Comment by Fetz** [comment]
please reopen this issue if any issue with skippable
