### ISSUE TITLE
Ad not playing with preload option set to "none"

### ISSUE THREAD

**Issue by indieveed** [MailOnline/videojs-vast-vpaid#41]
Hello,

I tried to change videojs' preload option to "auto" (via changing videoTag variable in createVideoEl function in demo_bundle.js). As a result when I hit "play" button preloader animation is starting, and after a timeout ad is canceled and content video starts playing. At that time I can see an exception thrown:

`AD ERROR: VAST Error: timeout while waiting for the video to start playing`

 If I disable ads, content video starts playing almost immediatly. I tried to set larger timeout intervals without any success.

**Comment by carpasse** [comment]
@indieveed Thanks for reporting the issue. 
Do you have a tag we can use to try to reproduce the issue?

**Comment by indieveed** [comment]
@carpasse I used tags from the demo page, just changed preload attribute in html

**Comment by sithmel** [comment]
@indieveed we are having a look

**Comment by sithmel** [comment]
When the preload attribute of the video element is "none", changing the source doesn't trigger the "durationchange" event (of course as we can't preload the video!).
This event is used to check whether the ad is a valid video and therefore for triggering the play.

**Comment by carpasse** [comment]
@indieveed We will do a release today or at the latest tomorrow containing the fix for this issue

**Comment by indieveed** [comment]
@carpasse @sithmel thanks, but what if I need to set the preload option to "none"? For example, when there is a lot of videos on the page and we want  them to start loading only after some action (click, scroll)? It may be useful on mobile.

**Comment by carpasse** [comment]
@indieveed We need to ensure the preload option to be auto before we change the src of the player with the new ad. This is necessary for IOS, slow browsers and heavy pages. If not we could start playing the video content instead of the ad video. On IOS sometimes it just throws an error and does nothing. 

If you take a look at the fix we only set the preload option to auto whenever we are about to change the src with the ad's video. This will only happen once the user has clicked on play therefore it will not download/buffer any video that is not going to be played.

Is this not good enough for you?

**Comment by indieveed** [comment]
@carpasse thanks for explanation, think the fix is good enough
