### ISSUE TITLE
Viewability Issue? 

### ISSUE THREAD

**Issue by orcaman** [MailOnline/videojs-vast-vpaid#51]
Hey guys,

I am seeing something weird with the player. I have ran some tests using real LiveRail demand, and it seems that the player produces less ad impressions there our in house player (which is 100% flash based). 

The main issue with your player seems to be related to viewability. It seems that LiveRail for some reason seems to think the player is not viewable.

For example, if you use the LiveRail test tag on your demo, you will see a request (not the first one) to liverail's domain, with POST data containing several LR_ vars.

One of them is this:
LR_VIEWABLE:2

If you use the same tag on JW Player (here http://demo.jwplayer.com/ad-tester/), you will see
LR_VIEWABLE:1

Could it be something in the styling? It looks like for some reason on some cases LiveRail considers the player not viewable and thus it produces less ad impressions.

Cheers,
Or

**Comment by joshmadewell** [comment]
I just reached out to our LR expert here in the office about this and got the following back:

This is what I got on it from documentation from April 2014:

We measure the video area at initAd() time. If any of the following are true, then LR_VIEWABLE is set to 2 (false):
- the viewable area is less than 50%
- the browser tab is not selected
- the browser application is in the background

If the ad is in an unfriendly iframe, LR_VIEWABLE is set to 0 (indeterminate).

Otherwise, LR_VIEWABLE is set to 1 (true).



Honestly - Don't think we are using this at this point!

**Comment by orcaman** [comment]
Hey @joshmadewell , thanks for your feedback. It's very helpful. 

If LR_VIEWABLE is in fact not being used at LR, I don't see a reason to keep this issue open. Closing.

**Comment by carpasse** [comment]
Wow I was starting to take a look at this issue and you already solved yourself. I am sorry for the late response it has been a busy month and we have not been able to keep up with the issues.

@orcaman and @joshmadewell thanks a lot for the issue and the solution we really appreciate your effort.

**Comment by orcaman** [comment]
@carpasse my pleasure. It would be great if you guys have some LR contacts that confirm this LR_VIEWABLE thing isn't in fact being used by them.

**Comment by carpasse** [comment]
@orcaman I have reached our commercial team asking about the LR_VIEWABLE.
