### ISSUE TITLE
VPAID ads on mobile

### ISSUE THREAD

**Issue by junaidtufail** [MailOnline/videojs-vast-vpaid#54]
VPAID ads are not showing on mobile. Any plans for that?

**Comment by carpasse** [comment]
Do you mean HTML VPAID ads??
Can you tell me in what platform have you tested them??

**Comment by junaidtufail** [comment]
yes any VPAID ad. 
I have tested on Iphone. Not working on iphone.

**Comment by carpasse** [comment]
Flash VPAID ads are never going to work because flash is not supported on any mobile platform. They are now also being blocked on some major desktop browsers like chrome and Safari by default.

Html VPAID ads are partially supported on mobile platforms.

By partially I mean that they mostly work on android devices and IPads (if you don't go on fullScreen mode as the native player kicks in when you go full screen). Unfortunately on iPhones and window phones they only play the video in their native player and no interactions are allowed (because the native player kicks in). This is a limitation of the platform and there is nothing we can do about it.

You also need to take into account that VPAID ads are much heavier than normal VAST ads therefore is more easier to get timeouts in a 3G or 4G connections. 

@junaidtufail if you have an HTML VPAID tag that it is not working on android or IPad please share it with us and we will test it.

**Comment by junaidtufail** [comment]
okay thanks

**Comment by alfuken** [comment]
> This is a limitation of the platform and there is nothing we can do about it.

Oh really?! How come [this](https://googleads.github.io/videojs-ima/examples/simple/) working, then?

**Comment by carpasse** [comment]
That is a VAST ad (only a video with some tracking) this issue is regarding VPAID interactive ads. Something that is not supported on IOS devices because the native player kicks in and you can not put buttons on top of if for example if you are able to play a VPAID HTML Ad (an interactive ad with buttons and links on top that can extend the duration amono other things) on an IOS device, please let us knowl

**Comment by codeorelse** [comment]
@alfuken The VAST ad at your [link](https://googleads.github.io/videojs-ima/examples/simple/) doesn't play on my iPhone 6. Does it work on your iPhone?
