### ISSUE TITLE
Why you don't use official video.js ads plugin?

### ISSUE THREAD

**Issue by gangstaJS** [MailOnline/videojs-vast-vpaid#58]
Why you don't use official video.js ads plugin?

**Comment by carpasse** [comment]
Hi @gangstaJS 

I imagine that you are referring to the videojs-contrib-ads plugin from videojs. We really tried to use it and we did use the contribs ads plugin for quite some time. We decided to stop using it about 2 months ago. Below I am going to try to explain you the reasons why we decided to stop using it.

**The documentation was not as good as we would have liked**
They have some documentation and it gets better with every version but up to version 2.0 we had to read the code of the plugin from top to bottom to be able to fully understand what had changed on every migration. 

**We felt that we were sacrificing too much flexibility**
The plugin decided when to start the ad, how to start it, and how to resume the content after the ad has played. It also limited the type of ads you could support. 

In the end it is a black box that tells you when to play the ad and the resulting code is not very easy to read/understand. You need to fully understand the contribs ads plugin to be able to understand the code. 

We had some issues on mobile devices where the preroll ad started after the content video had started playing (some times up to 10 seconds of content before the ad started playing). This was not the fault of the plugin itself. The problem was that our page is very heavy and the media evt were not always triggered when they were supposed to be triggered. While not considering it the plugin's fault we struggled to fix it because we could not decide when to start the ad as this was the responsibility of the contrib ads.

**Migration of major versions where painful**
We started using the plugin with version 0.x and experienced the migration from 0.x to 1.x and from 1.x to 2.x

**Migrating from 0.x to 1.x**
At version 0.x the contrib-ads plugin would trigger an event every time their state machine changed states. On 1.x it no longer triggered those events. They also changed the names of other events. This changes were documented on the migration document and we were able to do the migration. Although the missing events made the migration a bit painful.

**Migrating from 1.x to 2.x**
This release contained huge changes. It added support for postrolls ads. Changed all the events of the player adding a prefix 'ad' to all the event. 
The postroll ads added new states to the contribs state machine and we were forced to do a hack in order to be able to replay videos. 
The new events were a huge change because they not only added a prefix to all the player events. They also stopped the propagation of all the original player events. This was a huge problem for us because it meant that if the player have the ads plugin it would behave differently than if the player didn't have the ads plugin. 

At some point 2 months ago we decided that we wanted to fully control the development cycle of our ads plugin.

I hope this helps you understand why we decided not use the videojs-contrib-ads plugin any more.
