### ISSUE TITLE
Release Process -- Should we use RELEASE branch or master?

### ISSUE THREAD

**Issue by joshmadewell** [MailOnline/videojs-vast-vpaid#60]
Hey Guys,

We have a few changes to the repo that we maintain ourselves because they are most likely features that you don't want added.

As such, when a release is made, we pull down your repo and manually merge the release into our copy of the repo. I noticed that there is  `RELEASE` branch with the latest release and  that it's 15 ahead of `master`. Is this the branch we should pull down moving forward?

I guess worth asking is: would you guys be open to implementing the ability to call `stopAd` from the browser? I think I mentioned this before and @Fetz  mentioned you would not be implementing it but that I could look at how `skipAd` was implemented to do it myself. We've gone ahead and done this. 

The reason we needed `stopAd` is because some our publishers require the ability for a user to close an ad after N seconds. VPAID spec requires us to call `stopAd` because the browser has stopped displaying the ad.

**Comment by carpasse** [comment]
Hi @joshmadewell 

This stop ad feature that you are commenting, is it a VAST feature or an specific feature required by some of your publishers? Something like a close button? I assume you need it only for VAST ads. Is that correct?

If you want to keep your fork up to date I would use the Master branch. We do all of our releases starting from Master and we put a lot of effort into having it stable. 

I imagine that you are a bit confused with the release branch. We have automated the release process through travis. If we want to do a release, we merge the master with one of the version branches (patch | minor | major) then travis execute the release which basically means:
  1 - Download and install all the dependencies
  2 - Generate a  new build of the plugin
  3 - Hard pushing the changes from the version branch to the release branch 
  4 - Updating the version number depending on what version branch we used (patch | minor | major) to do the release
  5 - Generate a tag with the new version number
  6 - Update the Demo page with the latest version of the plugin.

As a result of this the github history of the  version branches and the release brach is a bit confusing but since they are a 1 way branches it does not really matter that much.

We want to improve this process to fix the github history among other things but unfortunately we have yet to find the time to do so.

In case you want to know exactly how we are doing the release you can take a look at the [release script](https://github.com/MailOnline/videojs-vast-vpaid/blob/master/scripts/release)

**Comment by joshmadewell** [comment]
The stopAd feature is a close button on the UI that users can click after 10-15 seconds of the ad displaying. We then want to call stopAd because the VPAID spec says that we need to call that when the player is no longer displaying the ad.

As far as the release process goes. Should the `bin/` folder be getting updated in `master` when you guys release? In master it was last updated 14 days ago but the latest release was yesterday?

**Comment by carpasse** [comment]
Are you trying to implement a close button? We were going to implement one but decided against it after reading the [VPAID specification](http://www.iab.net/media/file/VPAID_2.0_Final_04-10-2012.pdf). 
```
2.3.1 Displaying the Ad Unit Creative 
The video advertising industry expects that an impression has indicated that an ad was viewed
by an end user. Therefore, the video player should ensure that no other visual elements from the video player, the webpage, or other ads, display over a video ad that is currently in
progress.
Also, since video ad creative are expected to adhere to industry guidelines that include a
“Close X” button, the video player should not include its own close button for VPAID ad units
...
```
Is this a special requirement from a publisher? How will you know when to show the close button? And how will you know if the adUnit has or has not implemented a close button?

Regarding the bin folder, If you need the updated bin folder, then you should fork/sync from the RELEASE branch as it is there where we push the generated bin folder.

**Comment by joshmadewell** [comment]
This is a special requirement. We always show the close button whether or not the creative has one. We require that the ad has been viewed for at least 10 seconds before the user is able to close. The problem we noticed was that nearly all of the creatives were coming back without a close button, something that wasn't acceptable to our publishers.

I honestly never saw 2.3.1 in the spec and now understand the hesitation for adding this feature.

--

As far as the release goes, I suppose I will just use the `RELEASE` branch moving forward as that now seems easiest. Thanks.

**Comment by carpasse** [comment]
I have discussed the matter about the close button with the team and we have decided not to add it as a feature. The main reason is that it goes again the specs.

Do you have any other question regarding the release branch and master?

**Comment by joshmadewell** [comment]
Nope, all good, thanks for your help. We'll continue to maintain our own version :D
