### ISSUE TITLE
Bypass CORS via Flash

### ISSUE THREAD

**Issue by gordonglas** [MailOnline/videojs-vast-vpaid#70]
On your demo page you say:
"Some ad's will throw "VAST Error: on VASTClient.requestVastXML, HTTP request error with status '-1'", because that adServer is not setting the http access control header, the reason why some video player's are able to play the ad's in firefox because they do the request by flash bypassing the browser".

I was wondering if you're working on adding this, or if you possibly know how it's being done (or have a link to a resource of how it can be done).

Looking at actionscript docs for "security.allowDomain"...
http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001490.html
..it says (regarding SWF versions):
Version 5. No cross-domain scripting restrictions.
Version 6. Cross-domain scripting security is introduced.

So I'm guessing I need to build a Version 5 or lower SWF? I'm new to Flash/Actionscript.

Thanks

**Comment by Fetz** [comment]
Hi @gordonglas, no we are not working on this because the server should serve the VAST response with the correct CORS headers see http://www.iab.net/media/file/VASTv3.0.pdf, page 16 (2.1.5.2 Cross Origin Resource Sharing (CORS) for JavaScript).

This happens in some servers because they only are expecting that the VAST response to be loaded by Flash, and Flash use a different way to handle CORS [source 1](http://www.adobe.com/devnet/archive/html5/articles/understanding-cross-origin-resource-sharing-cors.html), [source 2](http://tiffanybbrown.com/2011/10/10/html5-for-as3-developers-cross-domain-xml-and-cross-origin-resource-sharing/) than the browsers [source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).


Now regarding your other question:
No I don't think you need to use a old version of flash, because I expecting them to serve the ad's with the cross-domain.xml (Flash CORS). So if you having a lot of issues and with CORS and your adservers are not friendly to start serving the correct headers you could do the following:

If you get that error message when loading the VAST response then using the [ExternalInterface](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html) you can request some flash to load that XML and retrieve to the JS the result.

**Comment by gordonglas** [comment]
Thank you so much! I was able to get XML back via Flash, since our ad-tag provider has implemented a crossdomain.xml whitelist (just not the CORS headers for Javascript).
