### ISSUE TITLE
No cleanup after VPAID Flash ad

### ISSUE THREAD

**Issue by yonida** [MailOnline/videojs-vast-vpaid#88]
I tested on your demo page.
Used this tag: http://search.spotxchange.com/vast/2.00/79391?VPAID=1&content_page_url=localhost.playbuzz.com&cb=3202405928168446&player_width=300&player_height=250

You can see that after starting the player, the VPAID code adds a few elements to the DOM under the body tag.
When the ad finish, and content starts, the elements remain.

Shouldn't the player remove the new DOM elements after the ad finishes?

**Comment by Fetz** [comment]
I'm getting issues using that tag.
But I'm managed to replicate the issue using LiveRail flash sample tag in the demo page.

In reality the player removes the DOM elements that the player created to play the ad. But if the ad creates DOM elements it should remove them when the ad finishes, but sadly sometimes they don't.

```html
<script type="text/javascript" src="http://cdn-static.liverail.com/js/companions.js?20131002"></script>
```

I could try to intercept ad try to communicate with the outside world but could break some ads.
The fastest way to avoid this issue is to wrap the player around an iframe

**Comment by Fetz** [comment]
Since we don't control this we will close this issue
